### ISSUE TITLE
jams atom

### ISSUE THREAD

**Issue by thebigredgeek** [nicolaslopezj/atom-graphql-autocomplete#1]
If I start typing gql template literals, atom jams up and doesn't become responsive again. :(

**Comment by nicolaslopezj** [comment]
Can you post an example of the query?

**Comment by thebigredgeek** [comment]
```javascript
@graphql(gql`
```

can't even write the second backtick

**Comment by thebigredgeek** [comment]
.graphqlrc:

```json
{
  "request": {
    "url": "http://localhost:8001/graphql"
  }
}
```

atom version `1.12.6`

**Comment by thebigredgeek** [comment]
Running language-babel `2.48.5`, graphql-autocomplete `0.3.0`, and language-graphql `0.7.0`
